site:
  title: Red Cuadrangular
  start_page: ROOT::index.adoc
  robots: disallow
content:
  sources: 
  - url: .
    branches: HEAD
    start_path: ROOT
  - url: .
    branches: HEAD
    start_path: loco
  - url: .
    branches: HEAD
    start_path: portal
ui: 
  bundle:
    url: https://redcuadrangular.github.io/theme-bible/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    page-component-sort-order: ROOT, loco, portal
antora:
  extensions:
  - '@antora/lunr-extension'
